name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'

      - name: Generar Gradle Wrapper
        run: gradle wrapper --gradle-version 9.3.1

      - name: Dar permisos al Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Compilar APK
        run: ./gradlew assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Jarvis-debug-apk
          path: app/build/outputs/apk/debug/*.apk